### ISSUE TITLE
Sublime Text 2

### ISSUE THREAD

**Issue by neosoyo** [textmate/scilab.tmbundle#1]
Anyone are using this bundle in subl?

here is crashing everytime.. =(

**Comment by infininight** [comment]
Make sure you are using the 1.x branch:

https://github.com/textmate/scilab.tmbundle/tree/textmate-1.x

Sublime does not yet support some of the 2.0 grammar additions.

**Comment by neosoyo** [comment]
thank's infininight, i appreciate that!

**Comment by nsaleille** [comment]
Hi, do anyone know how to set up sublime text 2 with this bundle so as to run code lines directly into Scilab 5.4.1 ?
I have the "set syntax" but can't run any script. cmd+r doesn't work.

Thanks !
