### ISSUE TITLE
Sublime Text 2 - Scilab 5.4.1

### ISSUE THREAD

**Issue by nsaleille** [textmate/scilab.tmbundle#2]
Hi, do anyone know how to set up sublime text 2 with this bundle so as to run code lines directly into Scilab 5.4.1 ? I have the "set syntax" but can't run any script. cmd+r doesn't work. I'm not an XML programmer so I don't know how to change settings in the "commands" files.

Thanks in advance for your help !

**Comment by sorbits** [comment]
Sorry, we have nothing to do with Sublime Text 2 (or any other “TextMate inspired editor”).
